name: github-actions-test

on:
  push:
    branches: [main]

jobs:
  print-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0
        
      - name: docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: install JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: build react app
        run: |
          cd web
          cat <<EOF | sudo tee ./.env
          ${{ secrets.REACT_ENV }}
          EOF
          npm install
          npm run build
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest






        
